version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: aquarium_postgres
    environment:
      POSTGRES_DB: aquarium_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aquarium-net

  app:
    build: .
    container_name: aquarium_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aquarium_store
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - aquarium-net

volumes:
  postgres_data:

networks:
  aquarium-net:
