version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aquarium_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aquarium-net

  backend:
    build: ./backend-project
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aquarium_store
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - aquarium-net

  frontend:
    build: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - aquarium-net

volumes:
  pgdata:

networks:
  aquarium-net: